import Link from "next/link";

const metrics = [["Obras em curso", "12", "+2 este mês", "blue"], ["Orçamentos pendentes", "8", "€ 86.400 em proposta", "orange"], ["Faturação do mês", "€ 42.680", "+12,5% vs. mês anterior", "green"], ["Tarefas concluídas", "68%", "34 de 50 tarefas", "purple"]];
const projects = [["Moradia Vale do Lobo", "João & Marta Silva", 78, "Em execução", "28 ago."], ["Remodelação Escritórios Axis", "Axis Consulting", 52, "Em execução", "04 set."], ["Apartamento Foz", "Inês Carvalho", 31, "Em preparação", "18 set."]];
const tasks = [["Validar medição da obra Vale do Lobo", "09:30"], ["Enviar orçamento para aprovação", "11:00"], ["Reunião de obra — Escritórios Axis", "15:30"], ["Atualizar documentos do Apartamento Foz", "17:00"]];

export default function DashboardPage() {
  return <div className="dashboard"><section className="page-intro"><div><p className="eyebrow">Visão geral</p><h2>Bom dia, Ricardo.</h2><p>Aqui está o resumo da atividade da sua empresa.</p></div><Link className="button button-primary" href="/obras">+ Nova obra</Link></section><section className="metric-grid">{metrics.map(([label, value, change, tone]) => <article className={`metric-card ${tone}`} key={label}><p>{label}</p><strong>{value}</strong><span>{change}</span></article>)}</section><section className="content-grid"><article className="panel"><div className="panel-heading"><div><h3>Obras em curso</h3><p>Acompanhe o estado dos projetos ativos.</p></div><Link href="/obras">Ver todas →</Link></div><div className="project-list">{projects.map(([name, client, progress, state, deadline]) => <div className="project-row" key={name}><div><strong>{name}</strong><span>{client}</span></div><div><div className="progress-label"><span>{state}</span><strong>{progress}%</strong></div><div className="progress-track"><span style={{ width: `${progress}%` }} /></div></div><time>{deadline}</time></div>)}</div></article><article className="panel"><div className="panel-heading"><div><h3>Tarefas de hoje</h3><p>Terça-feira, 19 de agosto</p></div><button className="text-button" type="button">Ver agenda</button></div><div className="task-list">{tasks.map(([title, time]) => <label className="task" key={title}><input type="checkbox" /><span>{title}</span><time>{time}</time></label>)}</div><button className="add-task" type="button">+ Adicionar tarefa</button></article></section></div>;
}
