export const REGISTRATION_DOCUMENT_TYPES = {
  IDENTITY_CARD: "IDENTITY_CARD",
  NIF_PROOF: "NIF_PROOF",
  ADDRESS_PROOF: "ADDRESS_PROOF",
  COMPANY_REGISTRATION: "COMPANY_REGISTRATION",
  COMMERCIAL_CERTIFICATE: "COMMERCIAL_CERTIFICATE",
  ACTIVITY_PROOF: "ACTIVITY_PROOF",
  INSURANCE: "INSURANCE",
  LICENSE: "LICENSE",
  POWER_OF_ATTORNEY: "POWER_OF_ATTORNEY",
} as const;

export type RegistrationDocumentType =
  (typeof REGISTRATION_DOCUMENT_TYPES)[keyof typeof REGISTRATION_DOCUMENT_TYPES];
